"""
Helpers to show unambiguous application metadata in UI.

Goal:
- App version/release date come from templates (source of truth), not from user config that persists between installs.
- Build metadata (time, git commit/tag) comes from bom_categorizer/_build_meta.json generated by tools/update_version.py sync.
"""

from __future__ import annotations

import json
import os
import platform
import sys
from datetime import datetime
from typing import Optional, Dict, Any


def _read_json(path: str) -> Optional[dict]:
    try:
        if not os.path.exists(path):
            return None
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return None


def load_build_meta() -> Optional[dict]:
    """
    Loads build meta generated by tools/update_version.py sync.
    """
    try:
        base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # .../bom_categorizer
        return _read_json(os.path.join(base_dir, "_build_meta.json"))
    except Exception:
        return None


def _format_hhmm(iso_dt: str) -> Optional[str]:
    try:
        dt = datetime.fromisoformat(iso_dt)
        return dt.strftime("%H:%M")
    except Exception:
        return None


def get_app_meta_for_ui(cfg: Dict[str, Any], edition: str = "modern") -> Dict[str, Any]:
    """
    Returns a dict with fields ready for tooltip/About dialog.
    """
    app_info = (cfg or {}).get("app_info") or {}
    build = load_build_meta() or {}
    editions = build.get("editions") or {}
    ed = editions.get(edition) or {}
    repo = build.get("repo") or {}

    version = app_info.get("version") or ed.get("version") or "dev"
    release_date = app_info.get("release_date") or ed.get("release_date") or "N/A"
    generated_at = build.get("generated_at")

    return {
        "edition": app_info.get("edition") or ("Modern Edition" if edition == "modern" else "Standard"),
        "version": version,
        "release_date": release_date,
        "build_hhmm": _format_hhmm(generated_at) if generated_at else None,
        "generated_at": generated_at,
        "repo_commit": repo.get("commit"),
        "repo_branch": repo.get("branch"),
        "repo_describe": repo.get("describe"),
        "repo_dirty": repo.get("dirty"),
        "python": sys.version.split()[0],
        "platform": platform.platform(),
    }


def format_app_tooltip(meta: Dict[str, Any], config_path: Optional[str] = None) -> str:
    """
    Compact multi-line tooltip/About text.
    """
    lines = []
    lines.append(f"{meta.get('edition', 'BOM Categorizer')} v{meta.get('version', 'dev')}")
    lines.append("══════════════════════════════")
    lines.append(f"Релиз: {meta.get('release_date', 'N/A')}")
    if meta.get("generated_at"):
        lines.append(f"Сборка: {meta.get('generated_at')} (hh:mm: {meta.get('build_hhmm') or 'N/A'})")
    if meta.get("repo_describe") or meta.get("repo_commit"):
        lines.append("")
        lines.append("Git:")
        if meta.get("repo_describe"):
            lines.append(f"  describe: {meta.get('repo_describe')}")
        if meta.get("repo_commit"):
            lines.append(f"  commit:   {meta.get('repo_commit')}")
        if meta.get("repo_branch"):
            lines.append(f"  branch:   {meta.get('repo_branch')}")
        if meta.get("repo_dirty") is not None:
            lines.append(f"  dirty:    {meta.get('repo_dirty')}")
    lines.append("")
    lines.append(f"Python: {meta.get('python', 'N/A')}")
    lines.append(f"OS: {meta.get('platform', 'N/A')}")
    if config_path:
        lines.append("")
        lines.append(f"Config: {config_path}")
    return "\n".join(lines)

